# Generated by Django 3.0.6 on 2020-05-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
    ]
